# Generated by Django 4.2.7 on 2023-11-23 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="grade",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default=django.utils.timezone.now,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
