# Generated by Django 4.2.7 on 2023-11-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0002_userprofile_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to="social_media.userprofile"
            ),
        ),
    ]
