# Generated by Django 4.2.7 on 2023-11-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0003_userprofile_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="followers",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="social_media.userprofile"
            ),
        ),
    ]
