# Generated by Django 4.2.7 on 2023-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0006_alter_userprofile_followers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to="social_media.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="social_media.userprofile"
            ),
        ),
    ]
